#!/usr/bin/env python3
"""Generate modern-patch/assets/savesync/tables.js from the PokéRogue source.

Usage: build_savesync_tables.py <path to a pagefaultgames/pokerogue checkout>

The save file stores species and moves as numeric ids. "Copy Pokémon caught"
needs names for them, plus each starter's egg moves, so this pulls those lists
out of the game's own source files. Re-run it when the game adds species or moves.
"""
import json
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "modern-patch/assets/savesync/tables.js"


def parse_enum(path: Path, name: str) -> dict:
    """Return {member: value} for a TypeScript numeric enum with implicit increments."""
    text = path.read_text()
    body = re.search(r"export enum %s \{(.*?)\n\}" % name, text, re.S)
    if not body:
        sys.exit(f"enum {name} not found in {path}")
    cleaned = re.sub(r"/\*.*?\*/", "", body.group(1), flags=re.S)
    cleaned = re.sub(r"//[^\n]*", "", cleaned)
    members = {}
    value = -1
    for entry in cleaned.split(","):
        entry = entry.strip()
        if not entry:
            continue
        match = re.fullmatch(r"(\w+)(?:\s*=\s*(-?\d+))?", entry)
        if not match:
            sys.exit(f"cannot parse {name} member: {entry!r}")
        value = int(match.group(2)) if match.group(2) is not None else value + 1
        members[match.group(1)] = value
    return members


def parse_const(path: Path, name: str) -> dict:
    """Return {member: value} for `export const Name = { MEMBER: 0, ... }`."""
    body = re.search(r"export const %s = \{(.*?)\n\}" % name, path.read_text(), re.S)
    if not body:
        sys.exit(f"const {name} not found in {path}")
    return {m: int(v) for m, v in re.findall(r"^\s*(\w+):\s*(-?\d+)", body.group(1), re.M)}


def pretty(member: str) -> str:
    return " ".join(word.capitalize() for word in member.split("_"))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    game = Path(sys.argv[1])
    species = parse_enum(game / "src/enums/species-id.ts", "SpeciesId")
    moves = parse_enum(game / "src/enums/move-id.ts", "MoveId")
    natures = parse_enum(game / "src/enums/nature.ts", "Nature")
    berries = parse_enum(game / "src/enums/berry-type.ts", "BerryType")
    types = {m: v for m, v in parse_enum(game / "src/enums/pokemon-type.ts", "PokemonType").items() if v >= 0}
    biome_file = game / "src/enums/biome-id.ts"
    biomes = parse_const(biome_file, "BiomeId") if "export const BiomeId" in biome_file.read_text() \
        else parse_enum(biome_file, "BiomeId")

    egg_text = (game / "src/data/balance/moves/egg-moves.ts").read_text()
    egg_moves = {}
    for name, listed in re.findall(r"\[SpeciesId\.(\w+)\]:\s*\[([^\]]*)\]", egg_text):
        ids = [moves[m] for m in re.findall(r"MoveId\.(\w+)", listed)]
        if len(ids) != 4:
            sys.exit(f"expected 4 egg moves for {name}, found {len(ids)}")
        egg_moves[species[name]] = ids
    if len(egg_moves) < 500:
        sys.exit(f"only {len(egg_moves)} starters found; the source format probably changed")

    tables = {
        "species": {value: pretty(name) for name, value in species.items()},
        "moves": {value: pretty(name) for name, value in moves.items()},
        "natures": [pretty(name) for name, _ in sorted(natures.items(), key=lambda item: item[1])],
        # One entry per starter (base form); the fourth egg move is the rare one.
        "eggMoves": egg_moves,
        # For describing runs in progress in backups.
        "biomes": {value: pretty(name) for name, value in biomes.items()},
        # For describing held items in "Copy current team".
        "berries": {value: pretty(name) for name, value in berries.items()},
        "types": {value: pretty(name) for name, value in types.items()},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_savesync_tables.py from the PokéRogue source. Do not edit.\n"
        "window.__saveTables = " + json.dumps(tables, separators=(",", ":"), ensure_ascii=False) + ";\n"
    )
    print(f"{len(tables['species'])} species, {len(tables['moves'])} moves, {len(biomes)} biomes, "
          f"{len(tables['natures'])} natures, {len(egg_moves)} starters -> {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
